name: 'GitHub Push'
description: 'Pushing to GitHub repository local changes'
author: 'ad-m'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: false
    default: ${{ github.token }}
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: false
    default: ${{ github.server_url }}
  ssh:
    description: 'Specify if ssh should be used'
    required: false
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
  force:
    description: 'Determines if force push is used'
    required: false
  force_with_lease:
    description: 'Determines if force-with-lease push is used'
    required: false
  atomic:
    description: 'Determines if atomic push is used, default true'
    required: false
  push_to_submodules:
    description: 'Determines if --recurse-submodules=<strategy> is used. The value defines the used strategy'
    required: false
    default: 'on-demand'
  tags:
    description: 'Determines if --tags is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
runs:
  using: 'node20'
  main: 'start.js'
